// src/seed/student.data.ts

import { Residence } from '../shared/entities/residence.entity';
import { Student } from '../users/entities/student.entity';

export const sampleStudents: Partial<Student>[] =
  [
    {
      student_id: 1006,
      first_name: 'Esther',
      last_name: 'Njoki',
      email: 'esther.njoki@ueab.ac.ke',
      phone_number: '+254701000006',
      gender: 'Female',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2002-11-05'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.3,
      credit_hours: 76,
      school: { id: 2 } as any, // Education, Humanities and Social Sciences
      department: { id: 3 } as any, // Education
      program: { id: 6 } as any, // BEd in Sciences
      residence: { id: 2 } as Residence, // Ladies' Dorm
    },
    {
      student_id: 1007,
      first_name: 'Mohamed',
      last_name: 'Ali',
      email: 'mohamed.ali@ueab.ac.ke',
      phone_number: '+254701000007',
      gender: 'Male',
      tribe: 'Somali',
      region: 'North Eastern',
      date_of_birth: new Date('2001-08-20'),
      nationality: 'Somali',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.4,
      credit_hours: 90,
      school: { id: 2 } as any,
      department: { id: 3 } as any,
      program: { id: 5 } as any,
      residence: { id: 3 } as Residence, // Off Campus Male
    },
    {
      student_id: 1008,
      first_name: 'Grace',
      last_name: 'Wambui',
      email: 'grace.wambui@ueab.ac.ke',
      phone_number: '+254701000008',
      gender: 'Female',
      tribe: 'Meru',
      region: 'Eastern',
      date_of_birth: new Date('2003-03-12'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 2.9,
      credit_hours: 58,
      school: { id: 1 } as any, // Business
      department: { id: 1 } as any, // Accounting
      program: { id: 1 } as any, // BBA in Accounting
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1009,
      first_name: 'Kevin',
      last_name: 'Mwangi',
      email: 'kevin.mwangi@ueab.ac.ke',
      phone_number: '+254701000009',
      gender: 'Male',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2001-12-30'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 3.1,
      credit_hours: 84,
      school: { id: 1 } as any,
      department: { id: 1 } as any,
      program: { id: 2 } as any, // Diploma in Finance
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1010,
      first_name: 'Maria',
      last_name: 'Santos',
      email: 'maria.santos@ueab.ac.ke',
      phone_number: '+254701000010',
      gender: 'Female',
      tribe: 'Luhya',
      region: 'Western',
      date_of_birth: new Date('2002-06-17'),
      nationality: 'Ugandan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.6,
      credit_hours: 82,
      school: { id: 1 } as any,
      department: { id: 2 } as any, // Management
      program: { id: 3 } as any,
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1011,
      first_name: 'Brian',
      last_name: 'Otieno',
      email: 'brian.otieno@ueab.ac.ke',
      phone_number: '+254701000011',
      gender: 'Male',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2002-10-01'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.2,
      credit_hours: 72,
      school: { id: 1 } as any,
      department: { id: 2 } as any,
      program: { id: 4 } as any, // MBA in Leadership
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1012,
      first_name: 'Caroline',
      last_name: 'Mutua',
      email: 'caroline.mutua@ueab.ac.ke',
      phone_number: '+254701000012',
      gender: 'Female',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2003-04-22'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 2.8,
      credit_hours: 61,
      school: { id: 3 } as any,
      department: { id: 6 } as any,
      program: { id: 11 } as any,
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1013,
      first_name: 'David',
      last_name: 'Ouma',
      email: 'david.ouma@ueab.ac.ke',
      phone_number: '+254701000013',
      gender: 'Male',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2000-11-10'),
      nationality: 'Kenyan',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 3.0,
      credit_hours: 100,
      school: { id: 3 } as any,
      department: { id: 6 } as any,
      program: { id: 12 } as any, // Diploma in Lab Diagnostics
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1014,
      first_name: 'Linet',
      last_name: 'Korir',
      email: 'linet.korir@ueab.ac.ke',
      phone_number: '+254701000014',
      gender: 'Female',
      tribe: 'Kalenjin',
      region: 'Rift Valley',
      date_of_birth: new Date('2001-07-09'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.4,
      credit_hours: 89,
      school: { id: 3 } as any,
      department: { id: 7 } as any, // Public Health
      program: { id: 13 } as any, // BSc in Public Health
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1015,
      first_name: 'Joel',
      last_name: 'Maina',
      email: 'joel.maina@ueab.ac.ke',
      phone_number: '+254701000015',
      gender: 'Male',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2002-09-05'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.1,
      credit_hours: 70,
      school: { id: 3 } as any,
      department: { id: 7 } as any,
      program: { id: 14 } as any, // Certificate in Epidemiology
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1016,
      first_name: 'Angela',
      last_name: 'Muteshi',
      email: 'angela.muteshi@ueab.ac.ke',
      phone_number: '+254701000016',
      gender: 'Female',
      tribe: 'Luhya',
      region: 'Western',
      date_of_birth: new Date('2003-02-10'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.0,
      credit_hours: 52,
      school: { id: 2 } as any,
      department: { id: 4 } as any, // Humanities and Social Sciences
      program: { id: 7 } as any, // BA in History
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1017,
      first_name: 'Samuel',
      last_name: 'Gatobu',
      email: 'samuel.gatobu@ueab.ac.ke',
      phone_number: '+254701000017',
      gender: 'Male',
      tribe: 'Meru',
      region: 'Eastern',
      date_of_birth: new Date('2001-10-15'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.4,
      credit_hours: 86,
      school: { id: 2 } as any,
      department: { id: 4 } as any,
      program: { id: 8 } as any, // BA in Sociology
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1018,
      first_name: 'Miriam',
      last_name: 'Ngugi',
      email: 'miriam.ngugi@ueab.ac.ke',
      phone_number: '+254701000018',
      gender: 'Female',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2002-05-19'),
      nationality: 'Ugandan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.3,
      credit_hours: 78,
      school: { id: 2 } as any,
      department: { id: 5 } as any, // Theology and Religious Studies
      program: { id: 9 } as any, // BA in Theology
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1019,
      first_name: 'James',
      last_name: 'Kiptoo',
      email: 'james.kiptoo@ueab.ac.ke',
      phone_number: '+254701000019',
      gender: 'Male',
      tribe: 'Kalenjin',
      region: 'Rift Valley',
      date_of_birth: new Date('2002-03-28'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.2,
      credit_hours: 74,
      school: { id: 2 } as any,
      department: { id: 5 } as any,
      program: { id: 10 } as any, // Diploma in Religious Education
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1020,
      first_name: 'Nadia',
      last_name: 'Mohammed',
      email: 'nadia.mohammed@ueab.ac.ke',
      phone_number: '+254701000020',
      gender: 'Female',
      tribe: 'Swahili',
      region: 'Coast',
      date_of_birth: new Date('2001-06-11'),
      nationality: 'Tanzanian',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.5,
      credit_hours: 92,
      school: { id: 4 } as any,
      department: { id: 8 } as any,
      program: { id: 16 } as any, // Diploma in Nursing Practice
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1021,
      first_name: 'Victor',
      last_name: 'Wanyama',
      email: 'victor.wanyama@ueab.ac.ke',
      phone_number: '+254701000021',
      gender: 'Male',
      tribe: 'Luhya',
      region: 'Western',
      date_of_birth: new Date('2001-04-30'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.4,
      credit_hours: 87,
      school: { id: 4 } as any,
      department: { id: 8 } as any,
      program: { id: 15 } as any, // BSc in Nursing
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1022,
      first_name: 'Blessing',
      last_name: 'Okoye',
      email: 'blessing.okoye@ueab.ac.ke',
      phone_number: '+254701000022',
      gender: 'Female',
      tribe: 'Igbo',
      region: 'West Africa',
      date_of_birth: new Date('2002-08-12'),
      nationality: 'Nigerian',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.6,
      credit_hours: 88,
      school: { id: 4 } as any,
      department: { id: 8 } as any,
      program: { id: 15 } as any,
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1023,
      first_name: 'Elijah',
      last_name: 'Mutai',
      email: 'elijah.mutai@ueab.ac.ke',
      phone_number: '+254701000023',
      gender: 'Male',
      tribe: 'Kalenjin',
      region: 'Rift Valley',
      date_of_birth: new Date('2002-01-25'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 2.9,
      credit_hours: 64,
      school: { id: 5 } as any,
      department: { id: 11 } as any,
      program: { id: 22 } as any, // BSc in Info Systems
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1024,
      first_name: 'Mercy',
      last_name: 'Waithera',
      email: 'mercy.waithera@ueab.ac.ke',
      phone_number: '+254701000024',
      gender: 'Female',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2003-09-17'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.0,
      credit_hours: 60,
      school: { id: 5 } as any,
      department: { id: 11 } as any,
      program: { id: 21 } as any,
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1025,
      first_name: 'Daniel',
      last_name: 'Okoth',
      email: 'daniel.okoth@ueab.ac.ke',
      phone_number: '+254701000025',
      gender: 'Male',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2001-05-06'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.3,
      credit_hours: 84,
      school: { id: 5 } as any,
      department: { id: 11 } as any,
      program: { id: 21 } as any,
      residence: { id: 3 } as Residence,
    },

    {
      student_id: 1026,
      first_name: 'Linet',
      last_name: 'Anyango',
      email: 'linet.anyango@ueab.ac.ke',
      phone_number: '+254701000026',
      gender: 'Female',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2001-11-09'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.4,
      credit_hours: 85,
      school: { id: 5 } as any,
      department: { id: 12 } as any, // Maths, Chem & Physics
      program: { id: 23 } as any, // BSc in Mathematics
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1027,
      first_name: 'Ahmed',
      last_name: 'Farah',
      email: 'ahmed.farah@ueab.ac.ke',
      phone_number: '+254701000027',
      gender: 'Male',
      tribe: 'Somali',
      region: 'North Eastern',
      date_of_birth: new Date('2002-02-20'),
      nationality: 'Somali',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.0,
      credit_hours: 72,
      school: { id: 5 } as any,
      department: { id: 12 } as any,
      program: { id: 24 } as any, // BSc in Chemistry
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1028,
      first_name: 'Eunice',
      last_name: 'Mumo',
      email: 'eunice.mumo@ueab.ac.ke',
      phone_number: '+254701000028',
      gender: 'Female',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2003-03-14'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 2.9,
      credit_hours: 55,
      school: { id: 5 } as any,
      department: { id: 13 } as any, // Tech & Applied Sci
      program: { id: 25 } as any, // BSc in Applied Tech
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1029,
      first_name: 'Joseph',
      last_name: 'Mwangi',
      email: 'joseph.mwangi@ueab.ac.ke',
      phone_number: '+254701000029',
      gender: 'Male',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2001-07-08'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.6,
      credit_hours: 90,
      school: { id: 5 } as any,
      department: { id: 13 } as any,
      program: { id: 26 } as any, // Diploma in Engineering
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1030,
      first_name: 'Brenda',
      last_name: 'Odinga',
      email: 'brenda.odinga@ueab.ac.ke',
      phone_number: '+254701000030',
      gender: 'Female',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2002-06-15'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.3,
      credit_hours: 70,
      school: { id: 5 } as any,
      department: { id: 10 } as any, // Foods, Nutrition & Dietetics
      program: { id: 20 } as any, // Diploma in Dietetics
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1031,
      first_name: 'Patrick',
      last_name: 'Oketch',
      email: 'patrick.oketch@ueab.ac.ke',
      phone_number: '+254701000031',
      gender: 'Male',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2002-04-02'),
      nationality: 'Ugandan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.1,
      credit_hours: 65,
      school: { id: 3 } as any,
      department: { id: 7 } as any, // Public Health
      program: { id: 13 } as any, // BSc in Public Health
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1032,
      first_name: 'Rose',
      last_name: 'Nabwire',
      email: 'rose.nabwire@ueab.ac.ke',
      phone_number: '+254701000032',
      gender: 'Female',
      tribe: 'Luhya',
      region: 'Western',
      date_of_birth: new Date('2003-03-03'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 3.0,
      credit_hours: 50,
      school: { id: 3 } as any,
      department: { id: 7 } as any,
      program: { id: 14 } as any, // Certificate in Epidemiology
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1033,
      first_name: 'Kelvin',
      last_name: 'Choge',
      email: 'kelvin.choge@ueab.ac.ke',
      phone_number: '+254701000033',
      gender: 'Male',
      tribe: 'Kalenjin',
      region: 'Rift Valley',
      date_of_birth: new Date('2001-12-01'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.4,
      credit_hours: 88,
      school: { id: 3 } as any,
      department: { id: 6 } as any, // Med Lab Sci
      program: { id: 12 } as any, // Diploma in Lab Diagnostics
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1034,
      first_name: 'Salma',
      last_name: 'Yussuf',
      email: 'salma.yussuf@ueab.ac.ke',
      phone_number: '+254701000034',
      gender: 'Female',
      tribe: 'Swahili',
      region: 'Coast',
      date_of_birth: new Date('2002-10-22'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.1,
      credit_hours: 72,
      school: { id: 5 } as any,
      department: { id: 9 } as any, // Bio Sci & Agriculture
      program: { id: 18 } as any, // BSc in Agriculture
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1035,
      first_name: 'Dennis',
      last_name: 'Otieno',
      email: 'dennis.otieno@ueab.ac.ke',
      phone_number: '+254701000035',
      gender: 'Male',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2000-05-05'),
      nationality: 'Kenyan',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 3.7,
      credit_hours: 120,
      school: { id: 5 } as any,
      department: { id: 9 } as any,
      program: { id: 17 } as any, // BSc in Biology
      residence: { id: 3 } as Residence,
    },

    {
      student_id: 1036,
      first_name: 'Grace',
      last_name: 'Mutheu',
      email: 'grace.mutheu@ueab.ac.ke',
      phone_number: '+254701000036',
      gender: 'Female',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2002-08-12'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.1,
      credit_hours: 66,
      school: { id: 5 } as any,
      department: { id: 10 } as any, // Foods, Nutrition and Dietetics
      program: { id: 19 } as any, // BSc in Human Nutrition
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1037,
      first_name: 'James',
      last_name: 'Ngugi',
      email: 'james.ngugi@ueab.ac.ke',
      phone_number: '+254701000037',
      gender: 'Male',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2001-04-21'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.3,
      credit_hours: 88,
      school: { id: 5 } as any,
      department: { id: 10 } as any,
      program: { id: 20 } as any, // Diploma in Dietetics
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1038,
      first_name: 'Amina',
      last_name: 'Hassan',
      email: 'amina.hassan@ueab.ac.ke',
      phone_number: '+254701000038',
      gender: 'Female',
      tribe: 'Somali',
      region: 'North Eastern',
      date_of_birth: new Date('2003-01-18'),
      nationality: 'Somali',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 3.0,
      credit_hours: 55,
      school: { id: 1 } as any,
      department: { id: 2 } as any, // Management
      program: { id: 4 } as any, // MBA in Leadership
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1039,
      first_name: 'Robert',
      last_name: 'Mutiso',
      email: 'robert.mutiso@ueab.ac.ke',
      phone_number: '+254701000039',
      gender: 'Male',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2002-11-30'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.2,
      credit_hours: 70,
      school: { id: 4 } as any,
      department: { id: 8 } as any, // Nursing
      program: { id: 15 } as any, // BSc in Nursing
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1040,
      first_name: 'Cynthia',
      last_name: 'Wairimu',
      email: 'cynthia.wairimu@ueab.ac.ke',
      phone_number: '+254701000040',
      gender: 'Female',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2000-10-25'),
      nationality: 'Kenyan',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 3.6,
      credit_hours: 110,
      school: { id: 4 } as any,
      department: { id: 8 } as any,
      program: { id: 16 } as any, // Diploma in Nursing Practice
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1041,
      first_name: 'Samuel',
      last_name: 'Wanyama',
      email: 'samuel.wanyama@ueab.ac.ke',
      phone_number: '+254701000041',
      gender: 'Male',
      tribe: 'Luhya',
      region: 'Western',
      date_of_birth: new Date('2002-03-03'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.1,
      credit_hours: 69,
      school: { id: 2 } as any,
      department: { id: 3 } as any, // Education
      program: { id: 5 } as any, // BEd in Arts
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1042,
      first_name: 'Hannah',
      last_name: 'Owino',
      email: 'hannah.owino@ueab.ac.ke',
      phone_number: '+254701000042',
      gender: 'Female',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2003-06-20'),
      nationality: 'Ugandan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 2.9,
      credit_hours: 50,
      school: { id: 2 } as any,
      department: { id: 4 } as any, // Humanities and Social Sciences
      program: { id: 7 } as any, // BA in History
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1043,
      first_name: 'Brian',
      last_name: 'Kiprotich',
      email: 'brian.kiprotich@ueab.ac.ke',
      phone_number: '+254701000043',
      gender: 'Male',
      tribe: 'Kalenjin',
      region: 'Rift Valley',
      date_of_birth: new Date('2001-02-12'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.4,
      credit_hours: 85,
      school: { id: 2 } as any,
      department: { id: 5 } as any, // Theology and Religious Studies
      program: { id: 9 } as any, // BA in Theology
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1044,
      first_name: 'Esther',
      last_name: 'Kendi',
      email: 'esther.kendi@ueab.ac.ke',
      phone_number: '+254701000044',
      gender: 'Female',
      tribe: 'Meru',
      region: 'Eastern',
      date_of_birth: new Date('2002-05-15'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.2,
      credit_hours: 70,
      school: { id: 2 } as any,
      department: { id: 5 } as any,
      program: { id: 10 } as any, // Diploma in Religious Education
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1045,
      first_name: 'Kevin',
      last_name: 'Mutua',
      email: 'kevin.mutua@ueab.ac.ke',
      phone_number: '+254701000045',
      gender: 'Male',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2000-09-18'),
      nationality: 'Tanzanian',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 3.5,
      credit_hours: 120,
      school: { id: 2 } as any,
      department: { id: 4 } as any, // Humanities and Social Sciences
      program: { id: 8 } as any, // BA in Sociology
      residence: { id: 3 } as Residence,
    },

    {
      student_id: 1046,
      first_name: 'Lilian',
      last_name: 'Cherono',
      email: 'lilian.cherono@ueab.ac.ke',
      phone_number: '+254701000046',
      gender: 'Female',
      tribe: 'Kalenjin',
      region: 'Rift Valley',
      date_of_birth: new Date('2001-03-19'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.4,
      credit_hours: 90,
      school: { id: 5 } as any,
      department: { id: 11 } as any, // Info Systems and Computing
      program: { id: 21 } as any, // BSc in Computer Science
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1047,
      first_name: 'Victor',
      last_name: 'Mwangi',
      email: 'victor.mwangi@ueab.ac.ke',
      phone_number: '+254701000047',
      gender: 'Male',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2002-11-11'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.0,
      credit_hours: 68,
      school: { id: 5 } as any,
      department: { id: 11 } as any,
      program: { id: 22 } as any, // BSc in Info Systems
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1048,
      first_name: 'Angela',
      last_name: 'Oketch',
      email: 'angela.oketch@ueab.ac.ke',
      phone_number: '+254701000048',
      gender: 'Female',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2003-07-23'),
      nationality: 'Ugandan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.3,
      credit_hours: 54,
      school: { id: 5 } as any,
      department: { id: 12 } as any, // Math, Chem, Physics
      program: { id: 23 } as any, // BSc in Mathematics
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1049,
      first_name: 'Dennis',
      last_name: 'Mutuku',
      email: 'dennis.mutuku@ueab.ac.ke',
      phone_number: '+254701000049',
      gender: 'Male',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2001-12-01'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 3.2,
      credit_hours: 85,
      school: { id: 5 } as any,
      department: { id: 12 } as any,
      program: { id: 24 } as any, // BSc in Chemistry
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1050,
      first_name: 'Nancy',
      last_name: 'Adhiambo',
      email: 'nancy.adhiambo@ueab.ac.ke',
      phone_number: '+254701000050',
      gender: 'Female',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2000-10-17'),
      nationality: 'Kenyan',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 3.6,
      credit_hours: 110,
      school: { id: 5 } as any,
      department: { id: 13 } as any, // Tech & Applied Sciences
      program: { id: 25 } as any, // BSc in Applied Tech
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1051,
      first_name: 'George',
      last_name: 'Otieno',
      email: 'george.otieno@ueab.ac.ke',
      phone_number: '+254701000051',
      gender: 'Male',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2002-01-03'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.2,
      credit_hours: 70,
      school: { id: 5 } as any,
      department: { id: 13 } as any,
      program: { id: 26 } as any, // Diploma in Engineering
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1052,
      first_name: 'Sophia',
      last_name: 'Kariuki',
      email: 'sophia.kariuki@ueab.ac.ke',
      phone_number: '+254701000052',
      gender: 'Female',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2001-05-29'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.5,
      credit_hours: 92,
      school: { id: 5 } as any,
      department: { id: 10 } as any, // Foods & Nutrition
      program: { id: 20 } as any, // Diploma in Dietetics
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1053,
      first_name: 'Ibrahim',
      last_name: 'Ali',
      email: 'ibrahim.ali@ueab.ac.ke',
      phone_number: '+254701000053',
      gender: 'Male',
      tribe: 'Somali',
      region: 'North Eastern',
      date_of_birth: new Date('2003-06-14'),
      nationality: 'Somali',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 3.0,
      credit_hours: 56,
      school: { id: 3 } as any,
      department: { id: 6 } as any,
      program: { id: 11 } as any,
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1054,
      first_name: 'Diana',
      last_name: 'Mwende',
      email: 'diana.mwende@ueab.ac.ke',
      phone_number: '+254701000054',
      gender: 'Female',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2001-02-08'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.4,
      credit_hours: 89,
      school: { id: 1 } as any,
      department: { id: 1 } as any,
      program: { id: 1 } as any,
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1055,
      first_name: 'Patrick',
      last_name: 'Musa',
      email: 'patrick.musa@ueab.ac.ke',
      phone_number: '+254701000055',
      gender: 'Male',
      tribe: 'Luhya',
      region: 'Western',
      date_of_birth: new Date('2002-07-27'),
      nationality: 'Congolese',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.1,
      credit_hours: 74,
      school: { id: 5 } as any,
      department: { id: 13 } as any,
      program: { id: 25 } as any,
      residence: { id: 1 } as Residence,
    },


    {
      student_id: 1056,
      first_name: 'Eunice',
      last_name: 'Njeri',
      email: 'eunice.njeri@ueab.ac.ke',
      phone_number: '+254701000056',
      gender: 'Female',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2002-05-01'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.3,
      credit_hours: 72,
      school: { id: 2 } as any,
      department: { id: 4 } as any, // Humanities & Social Sciences
      program: { id: 7 } as any, // BA in Sociology
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1057,
      first_name: 'Eric',
      last_name: 'Kimani',
      email: 'eric.kimani@ueab.ac.ke',
      phone_number: '+254701000057',
      gender: 'Male',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2001-06-11'),
      nationality: 'Kenyan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: false,
      isOnWorkProgram: true,
      gpa: 2.9,
      credit_hours: 85,
      school: { id: 2 } as any,
      department: { id: 5 } as any, // Theology
      program: { id: 9 } as any, // BA in Theology
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1058,
      first_name: 'Grace',
      last_name: 'Wanjiku',
      email: 'grace.wanjiku@ueab.ac.ke',
      phone_number: '+254701000058',
      gender: 'Female',
      tribe: 'Meru',
      region: 'Eastern',
      date_of_birth: new Date('2000-03-25'),
      nationality: 'Ugandan',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 3.7,
      credit_hours: 110,
      school: { id: 2 } as any,
      department: { id: 5 } as any,
      program: { id: 10 } as any, // Diploma in Religious Education
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1059,
      first_name: 'Joshua',
      last_name: 'Mutua',
      email: 'joshua.mutua@ueab.ac.ke',
      phone_number: '+254701000059',
      gender: 'Male',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2003-02-12'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.0,
      credit_hours: 55,
      school: { id: 2 } as any,
      department: { id: 4 } as any,
      program: { id: 6 } as any, // BA in History
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1060,
      first_name: 'Faith',
      last_name: 'Musyoka',
      email: 'faith.musyoka@ueab.ac.ke',
      phone_number: '+254701000060',
      gender: 'Female',
      tribe: 'Kamba',
      region: 'Eastern',
      date_of_birth: new Date('2001-08-08'),
      nationality: 'Tanzanian',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: true,
      gpa: 3.5,
      credit_hours: 84,
      school: { id: 2 } as any,
      department: { id: 3 } as any, // Education
      program: { id: 5 } as any, // BEd in Arts
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1061,
      first_name: 'Brian',
      last_name: 'Owino',
      email: 'brian.owino@ueab.ac.ke',
      phone_number: '+254701000061',
      gender: 'Male',
      tribe: 'Luo',
      region: 'Nyanza',
      date_of_birth: new Date('2000-10-05'),
      nationality: 'Kenyan',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 3.4,
      credit_hours: 112,
      school: { id: 2 } as any,
      department: { id: 4 } as any,
      program: { id: 7 } as any,
      residence: { id: 3 } as Residence,
    },
    {
      student_id: 1062,
      first_name: 'Mercy',
      last_name: 'Waithira',
      email: 'mercy.waithira@ueab.ac.ke',
      phone_number: '+254701000062',
      gender: 'Female',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2002-04-30'),
      nationality: 'Kenyan',
      admission_year: 2021,
      year_of_study: 3,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.3,
      credit_hours: 74,
      school: { id: 2 } as any,
      department: { id: 3 } as any,
      program: { id: 5 } as any,
      residence: { id: 2 } as Residence,
    },
    {
      student_id: 1063,
      first_name: 'Paul',
      last_name: 'Mugisha',
      email: 'paul.mugisha@ueab.ac.ke',
      phone_number: '+254701000063',
      gender: 'Male',
      tribe: 'Rwandese',
      region: 'Central',
      date_of_birth: new Date('2001-01-20'),
      nationality: 'Rwandan',
      admission_year: 2020,
      year_of_study: 4,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.2,
      credit_hours: 82,
      school: { id: 2 } as any,
      department: { id: 5 } as any,
      program: { id: 9 } as any,
      residence: { id: 1 } as Residence,
    },
    {
      student_id: 1064,
      first_name: 'Beatrice',
      last_name: 'Makena',
      email: 'beatrice.makena@ueab.ac.ke',
      phone_number: '+254701000064',
      gender: 'Female',
      tribe: 'Meru',
      region: 'Eastern',
      date_of_birth: new Date('2003-03-15'),
      nationality: 'Kenyan',
      admission_year: 2022,
      year_of_study: 2,
      status: 'Active',
      isRegistered: true,
      isOnWorkProgram: false,
      gpa: 3.1,
      credit_hours: 58,
      school: { id: 2 } as any,
      department: { id: 4 } as any,
      program: { id: 7 } as any,
      residence: { id: 4 } as Residence,
    },
    {
      student_id: 1065,
      first_name: 'Peter',
      last_name: 'Ndungu',
      email: 'peter.ndungu@ueab.ac.ke',
      phone_number: '+254701000065',
      gender: 'Male',
      tribe: 'Kikuyu',
      region: 'Central',
      date_of_birth: new Date('2000-07-07'),
      nationality: 'Kenyan',
      admission_year: 2019,
      year_of_study: 5,
      status: 'Graduated',
      isRegistered: false,
      isOnWorkProgram: false,
      gpa: 3.6,
      credit_hours: 115,
      school: { id: 2 } as any,
      department: { id: 3 } as any,
      program: { id: 5 } as any,
      residence: { id: 1 } as Residence,
    }
  ];
