// src/seed/student.data.ts

import { Student } from '../users/entities/student.entity';

export const sampleStudents: Partial<Student>[] = [
    {
        student_id: 1001,
        first_name: 'John',
        last_name: 'Omondi',
        email: 'john.omondi@ueab.ac.ke',
        phone_number: '+254701000001',
        gender: 'Male',
        tribe: 'Luo',
        region: 'Nyanza',
        date_of_birth: new Date('2002-04-12'),
        nationality: 'Kenyan',
        admission_year: 2021,
        year_of_study: 3,
        status: 'Active',
        school_name: 'Science & Technology',
        department_name: 'Computer Science',
        program_name: 'BSc Computer Science',
        program_id: 1,
        department_id: 10,
        residence: 'Hall A',
        isRegistered: true,
        isOnWorkProgram: false,
    },
    {
        student_id: 1002,
        first_name: 'Faith',
        last_name: 'Chebet',
        email: 'faith.chebet@ueab.ac.ke',
        phone_number: '+254701000002',
        gender: 'Female',
        tribe: 'Kalenjin',
        region: 'Rift Valley',
        date_of_birth: new Date('2001-09-23'),
        nationality: 'Kenyan',
        admission_year: 2020,
        year_of_study: 4,
        status: 'Active',
        school_name: 'Health Sciences',
        department_name: 'Nursing',
        program_name: 'BSc Nursing',
        program_id: 2,
        department_id: 11,
        residence: 'Hall B',
        isRegistered: true,
        isOnWorkProgram: true,
    },
    {
        student_id: 1003,
        first_name: 'Ali',
        last_name: 'Abdi',
        email: 'ali.abdi@ueab.ac.ke',
        phone_number: '+254701000003',
        gender: 'Male',
        tribe: 'Somali',
        region: 'North Eastern',
        date_of_birth: new Date('2003-01-15'),
        nationality: 'Kenyan',
        admission_year: 2022,
        year_of_study: 2,
        status: 'Active',
        school_name: 'Business',
        department_name: 'Accounting',
        program_name: 'BBA Accounting',
        program_id: 3,
        department_id: 12,
        residence: 'Hall C',
        isRegistered: false,
        isOnWorkProgram: false,
    },
    {
        student_id: 1004,
        first_name: 'Naomi',
        last_name: 'Kamau',
        email: 'naomi.kamau@ueab.ac.ke',
        phone_number: '+254701000004',
        gender: 'Female',
        tribe: 'Kikuyu',
        region: 'Central',
        date_of_birth: new Date('2000-12-30'),
        nationality: 'Kenyan',
        admission_year: 2019,
        year_of_study: 5,
        status: 'Graduated',
        school_name: 'Education',
        department_name: 'Languages',
        program_name: 'BA English',
        program_id: 4,
        department_id: 13,
        residence: 'Hall D',
        isRegistered: false,
        isOnWorkProgram: true,
    },
    {
        student_id: 1005,
        first_name: 'Tariq',
        last_name: 'Ahmed',
        email: 'tariq.ahmed@ueab.ac.ke',
        phone_number: '+254701000005',
        gender: 'Male',
        tribe: 'Coastal',
        region: 'Coast',
        date_of_birth: new Date('2002-07-07'),
        nationality: 'Kenyan',
        admission_year: 2021,
        year_of_study: 3,
        status: 'Active',
        school_name: 'Agriculture',
        department_name: 'AgriTech',
        program_name: 'BSc Agribusiness',
        program_id: 5,
        department_id: 14,
        residence: 'Hall E',
        isRegistered: true,
        isOnWorkProgram: true,
    },
];
